import { Search, Heart, Clock, RefreshCw, Download, Play, ArrowRight, Zap, X, ChevronRight, Shield, Cpu, Activity, Globe, ExternalLink, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import React, { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';

interface RelatedGame {
  id: string;
  title: string;
  image: string;
}

interface GameNode {
  id: string;
  title: string;
  image: string;
  status: 'INSTALLED' | 'AVAILABLE' | 'STEAM_CLOUD';
  hours: string;
  lastPlayed: string;
  liked: boolean;
  action: string;
  specs: { label: string; value: string }[];
  description: string;
  developer: string;
  publisher: string;
  releaseDate: string;
  genre: string;
  platforms: string[];
  fullSynopsis: string;
  appId?: string; // Steam App ID
  achievementProgress?: {
    completed: number;
    total: number;
    percentage: number;
  };
  steamMetadata?: {
    userReview: string;
    criticScore: number;
    tags: string[];
  };
  recommendedSpecs: { label: string; value: string }[];
  relatedGames: RelatedGame[];
}

const LIBRARY_NODES: GameNode[] = [
  {
    id: 'neon-protocol',
    title: "Neon Protocol",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800",
    status: 'INSTALLED',
    hours: "124 hrs",
    lastPlayed: "2 days ago",
    liked: false,
    action: "Play",
    specs: [
      { label: 'Engine', value: 'Vulkan' },
      { label: 'Latency', value: '8ms' },
      { label: 'Build', value: 'v4.2.1' }
    ],
    description: 'High-speed tactical infiltration. Master the corridors and bypass security grids.',
    developer: 'Cyber Core Systems',
    publisher: 'Void Industries',
    releaseDate: 'OCT 2025',
    genre: 'Tactical Stealth',
    platforms: ['Windows', 'Linux', 'Steam Deck'],
    fullSynopsis: 'In a world where data is the only currency, you are a ghost in the machine. Neon Protocol takes you through a series of high-stakes infiltration missions across the Tokyo Spires. Use advanced decryption tools and physical agility to navigate levels that react to your presence in real-time.',
    steamMetadata: {
      userReview: 'Overwhelmingly Positive',
      criticScore: 94,
      tags: ['Cyberpunk', 'Hardcore', 'First-Person']
    },
    recommendedSpecs: [
      { label: 'GPU', value: 'RTX_5090_ULTRA' },
      { label: 'RAM', value: '64GB_DDR6' },
      { label: 'OS', value: 'PRO_GAUGE_1.2' }
    ],
    relatedGames: [
      { id: 'shadow-tactics', title: 'Shadow Tactics', image: 'https://images.unsplash.com/photo-1614013410980-6e1307224211?auto=format&fit=crop&q=80&w=800' },
      { id: 'velocity-x', title: 'Velocity X', image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800' }
    ]
  },
  {
    id: 'velocity-x',
    title: "Velocity X",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=800",
    status: 'AVAILABLE',
    hours: "45 hrs",
    lastPlayed: "Not Installed",
    liked: true,
    action: "Install",
    specs: [
      { label: 'Engine', value: 'Neutron Drive' },
      { label: 'Physics', value: 'PhysX' },
      { label: 'Build', value: 'v1.0.4' }
    ],
    description: 'The fastest anti-gravity racing simulation. Break the sound barrier across modular tracks.',
    developer: 'Alt Vector Labs',
    publisher: 'Speed Sync',
    releaseDate: 'JAN 2026',
    genre: 'Racing Simulation',
    platforms: ['Windows', 'Console'],
    fullSynopsis: 'Velocity X ignores the laws of gravity. Compete in the Intergalactic Speed Circuit where tracks are generated by your performance. The faster you go, the more complex the modular environment becomes. Integrated with Neural-Sync for sub-millisecond response times.',
    steamMetadata: {
      userReview: 'Very Positive',
      criticScore: 88,
      tags: ['Racing', 'Fast-Paced', 'Sci-Fi']
    },
    recommendedSpecs: [
      { label: 'GPU', value: 'RTX_4080_TI' },
      { label: 'RAM', value: '32GB_DDR5' },
      { label: 'Storage', value: '250GB_NVME' }
    ],
    relatedGames: [
      { id: 'neon-protocol', title: 'Neon Protocol', image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800' }
    ]
  },
  {
    id: 'shadow-tactics',
    title: "Shadow Tactics",
    image: "https://images.unsplash.com/photo-1614013410980-6e1307224211?auto=format&fit=crop&q=80&w=800",
    status: 'INSTALLED',
    hours: "12 hrs",
    lastPlayed: "Today",
    liked: false,
    action: "Play",
    specs: [
      { label: 'AI Core', value: 'Strata Mind' },
      { label: 'Lighting', value: 'Ray Tracing' },
      { label: 'Build', value: 'v2.8.9' }
    ],
    description: 'Isometric tactical stealth. Command a group of elite operatives through highly secured sectors.',
    developer: 'Mind Sync Society',
    publisher: 'Strata Global',
    releaseDate: 'MAR 2025',
    genre: 'Tactical RPG',
    platforms: ['Windows', 'macOS', 'Linux'],
    fullSynopsis: 'Shadow Tactics puts you in command of the Strata-Mind, a central AI controlling five specialized clones. Orchestrate synchronized strikes, hack security perimeters, and ghost through high-security facilities in this isometric masterpiece of planning and execution.',
    steamMetadata: {
      userReview: 'Positive',
      criticScore: 82,
      tags: ['Strategy', 'Stealth', 'Isometric']
    },
    recommendedSpecs: [
      { label: 'CPU', value: 'INTEL_I9_CORE' },
      { label: 'RAM', value: '16GB_DDR5' },
      { label: 'Display', value: '4K_144HZ' }
    ],
    relatedGames: [
      { id: 'neon-protocol', title: 'Neon Protocol', image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800' }
    ]
  }
];

export function LibraryPage() {
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const [steamGames, setSteamGames] = useState<GameNode[]>([]);
  const [isSyncing, setIsSyncing] = useState(false);
  const [steamId, setSteamId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [activeFilter, setActiveFilter] = useState<'all' | 'local' | 'steam' | 'favorites'>('all');
  const [showSteamInput, setShowSteamInput] = useState(false);
  const [manualSteamId, setManualSteamId] = useState('');
  const [syncError, setSyncError] = useState<string | null>(null);

  useEffect(() => {
    const fetchProfile = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const { data, error } = await supabase
          .from('profiles')
          .select('steam_id')
          .eq('id', user.id)
          .single();
        
        if (!error && data?.steam_id) {
          setSteamId(data.steam_id);
        }
      }
    };
    fetchProfile();
  }, []);

  const syncSteamLibrary = async (idToUse?: string) => {
    const id = idToUse || steamId;
    if (!id) return;
    setIsSyncing(true);
    setSyncError(null);
    try {
      const response = await fetch(`/api/steam/games?steamId=${id}`);
      
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Connection to Steam API failed');
      }

      const data = await response.json();

      if (data.games) {
        const mappedGames: GameNode[] = data.games.map((g: any) => ({
          id: `steam-${g.appid}`,
          appId: g.appid.toString(),
          title: g.name,
          image: `https://cdn.akamai.steamstatic.com/steam/apps/${g.appid}/library_600x900.jpg`,
          status: 'STEAM_CLOUD',
          hours: `${Math.round(g.playtime_forever / 60)} hrs`,
          lastPlayed: g.playtime_2weeks ? `${Math.round(g.playtime_2weeks / 60)}h recent` : 'Idle',
          liked: false,
          action: 'PLAY',
          description: `Steam Library Entry: ${g.name}. Synchronized via global terminal.`,
          developer: 'N/A',
          publisher: 'N/A',
          releaseDate: 'N/A',
          genre: 'Steam Game',
          platforms: ['Steam'],
          fullSynopsis: `Remote record of ${g.name}. Access available via the Steam Protocol. Achievement tracking and playtime metrics are active for this node.`,
          specs: [{ label: 'Source', value: 'Steam Cloud' }],
          recommendedSpecs: [],
          relatedGames: []
        }));
        setSteamGames(mappedGames);
        setShowSteamInput(false);
        
        // Save to profile if manual ID was used
        if (idToUse) {
          const { data: { user } } = await supabase.auth.getUser();
          if (user) {
            await supabase
              .from('profiles')
              .upsert({
                id: user.id,
                steam_id: idToUse,
                updated_at: new Date().toISOString()
              }, { onConflict: 'id' });
          }
          setSteamId(idToUse);
        }
      } else {
        setSyncError('No games found. Is your library private?');
      }
    } catch (err: any) {
      console.error('Steam Sync Failed:', err);
      setSyncError(err.message || 'Synchronization failed');
    } finally {
      setIsSyncing(false);
    }
  };

  const filteredGames = [...LIBRARY_NODES, ...steamGames].filter(game => {
    const matchesSearch = game.title.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = 
      activeFilter === 'all' ? true :
      activeFilter === 'local' ? game.status === 'INSTALLED' :
      activeFilter === 'steam' ? game.status === 'STEAM_CLOUD' :
      activeFilter === 'favorites' ? game.liked : true;
    return matchesSearch && matchesFilter;
  });

  const selectedNode = [...LIBRARY_NODES, ...steamGames].find(n => n.id === selectedNodeId);

  // Fetch achievements for selected node if it's a Steam game
  useEffect(() => {
    if (selectedNode?.appId && (steamId || manualSteamId) && !selectedNode.achievementProgress) {
      const fetchAchievements = async () => {
        try {
          const id = steamId || manualSteamId;
          const res = await fetch(`/api/steam/achievements?steamId=${id}&appId=${selectedNode.appId}`);
          const data = await res.json();
          if (data.achievements) {
            const completed = data.achievements.filter((a: any) => a.achieved === 1).length;
            const total = data.achievements.length;
            const percentage = total > 0 ? Math.round((completed / total) * 100) : 0;
            
            const updatedGames = steamGames.map(g => 
              g.appId === selectedNode.appId 
                ? { ...g, achievementProgress: { completed, total, percentage } }
                : g
            );
            setSteamGames(updatedGames);
          }
        } catch (err) {
          console.error('Achievement Sycn Failed:', err);
        }
      };
      fetchAchievements();
    }
  }, [selectedNodeId, steamId, manualSteamId]);

  return (
    <div className="space-y-xl animate-in fade-in duration-700 pb-12">
      <AnimatePresence mode="wait">
        {!selectedNodeId ? (
          <motion.div 
            key="grid"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, scale: 0.98 }}
            className="space-y-xl"
          >
            {/* Search & Filters */}
            <section className="space-y-12">
              <div className="relative border-b border-white/20 pb-4 group">
                <Search className="absolute left-0 top-1/2 -translate-y-1/2 text-primary w-5 h-5 group-focus-within:scale-125 transition-transform" />
                <input 
                  type="text" 
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search Games..." 
                  className="w-full bg-transparent py-4 pl-10 pr-4 text-white font-black uppercase tracking-widest focus:outline-none placeholder:text-white/20"
                />
              </div>

              <div className="flex flex-wrap gap-4 scrollbar-hide items-center justify-between w-full">
                <div className="flex gap-4">
                  <FilterChip label="All Games" active={activeFilter === 'all'} onClick={() => setActiveFilter('all')} />
                  <FilterChip label="Local" active={activeFilter === 'local'} onClick={() => setActiveFilter('local')} />
                  <FilterChip label="Favorites" active={activeFilter === 'favorites'} onClick={() => setActiveFilter('favorites')} />
                  <FilterChip label="Steam Cloud" active={activeFilter === 'steam'} onClick={() => setActiveFilter('steam')} />
                </div>
                
                {steamId ? (
                  <div className="flex items-center gap-4">
                    {syncError && <span className="text-[9px] text-red-500 font-mono animate-pulse">{syncError}</span>}
                    <button 
                      disabled={isSyncing}
                      onClick={() => syncSteamLibrary()}
                      className="flex items-center gap-3 px-6 py-2 border border-primary/20 text-primary text-[10px] font-black uppercase tracking-widest hover:bg-primary/10 transition-all disabled:opacity-50"
                    >
                      {isSyncing ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
                      <span>{isSyncing ? 'Synchronizing...' : 'Sync Steam Library'}</span>
                    </button>
                  </div>
                ) : (
                  <div className="flex items-center gap-4">
                    {showSteamInput ? (
                      <div className="flex flex-col items-end gap-2">
                        <div className="flex items-center gap-2 animate-in slide-in-from-right-4">
                          <input 
                            type="text"
                            value={manualSteamId}
                            onChange={(e) => setManualSteamId(e.target.value)}
                            placeholder="17-DIGIT STEAM ID"
                            className="bg-white/5 border border-white/10 px-4 py-2 text-[10px] font-mono focus:outline-none focus:border-primary transition-colors text-white w-48"
                          />
                          <button 
                            onClick={() => syncSteamLibrary(manualSteamId)}
                            disabled={isSyncing || !manualSteamId}
                            className="px-4 py-2 bg-primary text-black text-[10px] font-black uppercase hover:bg-white transition-colors disabled:opacity-50"
                          >
                            {isSyncing ? <Loader2 className="w-3 h-3 animate-spin" /> : 'Sync'}
                          </button>
                          <button onClick={() => setShowSteamInput(false)} className="p-2 text-white/40 hover:text-white"><X className="w-4 h-4" /></button>
                        </div>
                        <div className="flex gap-4">
                          {syncError && <span className="text-[9px] text-red-500 font-mono">{syncError}</span>}
                          <a 
                            href="https://steamidfinder.com/" 
                            target="_blank" 
                            rel="noreferrer"
                            className="text-[8px] text-white/20 hover:text-primary transition-colors font-mono uppercase tracking-widest"
                          >
                            Find my Steam ID →
                          </a>
                        </div>
                      </div>
                    ) : (
                      <button 
                        onClick={() => setShowSteamInput(true)}
                        className="flex items-center gap-3 px-6 py-2 border border-white/10 text-white/40 text-[10px] font-black uppercase tracking-widest hover:border-primary hover:text-primary transition-all"
                      >
                        <Globe className="w-3 h-3" />
                        <span>Link Steam ID</span>
                      </button>
                    )}
                  </div>
                )}
              </div>
            </section>

            {/* Featured Section */}
            <section className="grid grid-cols-1 lg:grid-cols-12 gap-px bg-white/10 border border-white/10 overflow-hidden">
              <div className="lg:col-span-8 bg-white text-black p-12 lg:p-16 flex flex-col justify-between group cursor-pointer relative overflow-hidden">
                <div className="absolute top-[-20%] right-[-10%] p-8 opacity-5 group-hover:opacity-100 transition-all duration-1000 rotate-12 group-hover:rotate-0">
                  <Zap className="w-96 h-96" />
                </div>
                <div>
                  <span className="text-[10px] font-bold uppercase tracking-[0.3em] opacity-40">Featured Hub</span>
                  <h2 className="text-6xl md:text-8xl font-black uppercase tracking-tighter mt-4 leading-[0.8] transition-all">Vanguard</h2>
                  <p className="text-sm md:text-md font-serif italic mt-8 max-w-sm opacity-60 leading-relaxed">
                    Access the latest experimental builds and tactical simulations. Integrated support for multi-device synchronization.
                  </p>
                </div>
                <div className="mt-12 flex items-center gap-6 group">
                  <div className="w-16 h-16 border-2 border-black flex items-center justify-center group-hover:bg-black group-hover:text-white transition-all transform group-hover:scale-110">
                    <Play className="w-6 h-6 fill-current" />
                  </div>
                  <div className="flex flex-col">
                    <span className="text-[11px] font-black uppercase tracking-[0.2em]">Resume Game</span>
                    <span className="text-[9px] font-mono opacity-40 uppercase">Last Active: 2H Ago</span>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-4 bg-background p-12 flex flex-col justify-between border-t lg:border-t-0 lg:border-l border-white/10 group cursor-pointer hover:bg-white/[0.02] transition-colors relative h-full">
                <div className="absolute bottom-0 right-0 p-4 hidden lg:block">
                   <span className="text-[8px] font-mono text-white/5 uppercase vertical-text tracking-widest">SPOTLIGHT REF X99</span>
                </div>
                <div className="flex justify-between items-start">
                  <div className="flex flex-col">
                    <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-primary underline underline-offset-8">Spotlight</span>
                    <h3 className="text-4xl lg:text-5xl font-black uppercase tracking-tighter mt-6 leading-none">Stellar<br/>Frontier</h3>
                  </div>
                  <span className="text-[9px] font-mono text-white/20 uppercase tracking-widest">[EXPANSION]</span>
                </div>
                <div className="mt-12 flex items-center justify-between border-t border-white/10 pt-8">
                  <div className="flex flex-col">
                    <span className="text-4xl font-mono font-light italic">89 HRS</span>
                    <span className="text-[9px] font-mono text-white/20 uppercase mt-1">Playtime Logged</span>
                  </div>
                  <div className="w-12 h-12 border border-white/20 flex items-center justify-center group-hover:border-primary group-hover:bg-primary group-hover:text-black transition-all">
                    <ArrowRight className="w-6 h-6 group-hover:translate-x-1 transition-transform" />
                  </div>
                </div>
              </div>
            </section>

            {/* Game List Grid */}
            <div className="grid grid-cols-1 gap-px bg-white/10 border border-white/10">
              {filteredGames.map(node => (
                <GameRow 
                  key={node.id}
                  title={node.title}
                  image={node.image}
                  status={node.status}
                  hours={node.hours}
                  lastPlayed={node.lastPlayed}
                  liked={node.liked}
                  action={node.action}
                  onClick={() => setSelectedNodeId(node.id)}
                />
              ))}
              {filteredGames.length < (LIBRARY_NODES.length + steamGames.length) && (
                <div className="bg-primary p-12 flex flex-col justify-center items-center text-black cursor-pointer group hover:bg-white transition-colors">
                  <RefreshCw className="w-12 h-12 mb-4 group-hover:rotate-180 transition-transform duration-500" />
                  <span className="text-[10px] font-black uppercase tracking-[0.3em]">Load More</span>
                </div>
              )}
              {filteredGames.length === 0 && (
                <div className="py-32 flex flex-col items-center justify-center opacity-20 space-y-6">
                  <Search className="w-16 h-16" />
                  <span className="text-sm font-black uppercase tracking-[0.4em]">No matches found in grid</span>
                </div>
              )}
            </div>
          </motion.div>
        ) : (
          <motion.div 
            key="detail"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="border border-white/10 bg-white/[0.02] overflow-hidden flex flex-col"
          >
            {/* Detail Header */}
            <div className="p-6 border-b border-white/10 flex justify-between items-center bg-black/40 sticky top-0 z-10 backdrop-blur-md">
              <button 
                onClick={() => setSelectedNodeId(null)}
                className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-widest text-white/40 hover:text-white transition-all group"
              >
                <ArrowRight className="w-4 h-4 rotate-180 group-hover:-translate-x-1 transition-transform" />
                <span>Back to Library</span>
              </button>
              <div className="flex items-center gap-4">
                 <div className="hidden sm:flex items-center gap-4 border-r border-white/10 pr-4 mr-4">
                    <Activity className="w-4 h-4 text-primary" />
                    <span className="text-[10px] font-mono text-white/40 uppercase tracking-[0.2em] italic">Time Played: {selectedNode?.hours}</span>
                 </div>
                 <Shield className="w-4 h-4 text-primary animate-pulse" />
                 <span className="text-[10px] font-mono text-white/20 uppercase tracking-[0.5em]">Secure Connection</span>
                 <X className="w-5 h-5 text-white/20 hover:text-white cursor-pointer ml-4 transition-colors" onClick={() => setSelectedNodeId(null)} />
              </div>
            </div>

            <div className="flex-grow">
              {/* Hero Section */}
              <div className="grid grid-cols-1 lg:grid-cols-12 border-b border-white/10">
                <div className="lg:col-span-5 relative h-[400px] lg:h-[600px] overflow-hidden group border-r border-white/10">
                   <img 
                    src={selectedNode?.appId ? `https://cdn.akamai.steamstatic.com/steam/apps/${selectedNode.appId}/header.jpg` : selectedNode?.image} 
                    className="absolute inset-0 w-full h-full object-cover group-hover:scale-110 transition-transform duration-[10s] ease-out" 
                    alt="" 
                   />
                   <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent" />
                   <div className="absolute bottom-12 left-12 right-12">
                      <div className="flex items-center gap-4 mb-4">
                        <span className="px-3 py-1 bg-primary text-black text-[10px] font-bold uppercase tracking-widest">STATUS: {selectedNode?.status}</span>
                        <div className="h-[1px] flex-grow bg-white/20" />
                      </div>
                      <h2 className="text-6xl lg:text-8xl font-black uppercase tracking-[calc(-0.05em)] leading-[0.85] italic mb-4">{selectedNode?.title}</h2>
                      <div className="flex flex-wrap gap-2">
                        {selectedNode?.steamMetadata?.tags.map(tag => (
                          <span key={tag} className="text-[8px] font-mono text-white/40 border border-white/10 px-2 py-1 uppercase tracking-widest">{tag}</span>
                        ))}
                      </div>
                   </div>
                </div>

                <div className="lg:col-span-7 p-12 lg:p-16 flex flex-col justify-between bg-black/20">
                  <div className="space-y-16">
                     {/* Metadata Grid */}
                     <div className="grid grid-cols-2 md:grid-cols-4 gap-x-12 gap-y-8 border-b border-white/5 pb-12">
                        <MetadataItem label="Developer" value={selectedNode?.developer} />
                        <MetadataItem label="Publisher" value={selectedNode?.publisher} />
                        <MetadataItem label="Release Date" value={selectedNode?.releaseDate} />
                        <MetadataItem label="Genre" value={selectedNode?.genre} />
                        <MetadataItem label="Availability" value={selectedNode?.platforms.join(' / ')} />
                        {selectedNode?.steamMetadata && (
                          <>
                            <MetadataItem label="User Rating" value={selectedNode.steamMetadata.userReview} color="text-primary" />
                            <MetadataItem label="Critic Score" value={selectedNode.steamMetadata.criticScore.toString()} color="text-primary" />
                          </>
                        )}
                     </div>

                     {/* Synopsis */}
                     <div className="space-y-6">
                        <div className="flex items-center gap-3">
                           <Globe className="w-4 h-4 text-primary/40" />
                           <h4 className="text-[11px] font-bold uppercase tracking-[0.3em] italic text-white/60">Game Description</h4>
                        </div>
                        <p className="text-lg lg:text-xl font-serif italic text-white/80 leading-relaxed border-l-4 border-primary/20 pl-8 max-w-2xl">
                          {selectedNode?.fullSynopsis}
                        </p>
                     </div>
                  </div>

                  <div className="flex flex-col sm:flex-row gap-4 mt-20">
                     {selectedNode?.appId ? (
                       <a 
                         href={`steam://run/${selectedNode.appId}`}
                         className="flex-[2] py-6 bg-white text-black font-black uppercase tracking-[0.4em] text-[12px] hover:bg-primary transition-all flex items-center justify-center gap-4 relative overflow-hidden group"
                       >
                          <div className="absolute inset-0 bg-primary/20 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-500" />
                          <Play className="w-5 h-5 fill-current" />
                          <span>Launch Protocol</span>
                       </a>
                     ) : (
                       <button className="flex-[2] py-6 bg-white text-black font-black uppercase tracking-[0.4em] text-[12px] hover:bg-primary transition-all flex items-center justify-center gap-4 relative overflow-hidden group">
                          <div className="absolute inset-0 bg-primary/20 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-500" />
                          <Play className="w-5 h-5 fill-current" />
                          <span>{selectedNode?.action === 'Play' ? 'Play Game' : 'Install Game'}</span>
                       </button>
                     )}
                     
                     {selectedNode?.appId && (
                       <a 
                          href={`https://store.steampowered.com/app/${selectedNode.appId}`}
                          target="_blank"
                          rel="noreferrer"
                          className="flex-1 py-6 border border-white/10 text-white/40 font-black uppercase tracking-[0.4em] text-[11px] hover:border-white hover:text-white transition-all flex items-center justify-center gap-3"
                       >
                          <ExternalLink className="w-4 h-4" />
                          Store Page
                       </a>
                     )}
                  </div>
                </div>
              </div>

              {/* Technical Specs & Related Section */}
              <div className="grid grid-cols-1 lg:grid-cols-12 border-b border-white/10 bg-black/40">
                <div className="lg:col-span-8 p-12 lg:p-16 border-b lg:border-b-0 lg:border-r border-white/10">
                   <div className="flex items-center justify-between mb-12">
                      <div className="flex items-center gap-4">
                         <div className="w-2 h-8 bg-primary" />
                         <h3 className="text-2xl font-black uppercase tracking-widest italic">
                            {selectedNode?.appId ? 'Steam Metrics' : 'System Requirements'}
                         </h3>
                      </div>
                      <span className="text-[10px] font-mono text-white/20 uppercase tracking-[0.4em]">Compatibility: Pass</span>
                   </div>

                   <div className="grid grid-cols-1 md:grid-cols-2 gap-16">
                      {selectedNode?.appId ? (
                        <div className="col-span-2 space-y-12">
                           <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                              <MetricBox label="Integrity Score" value={`${selectedNode.achievementProgress?.percentage || 0}%`} sub="Achievement Sync" />
                              <MetricBox label="Milestones" value={`${selectedNode.achievementProgress?.completed || 0} / ${selectedNode.achievementProgress?.total || 0}`} sub="Tactical Peaks" />
                              <MetricBox label="App Identifier" value={`REF_${selectedNode.appId}`} sub="Global Network" />
                           </div>
                           
                           {selectedNode.achievementProgress && (
                             <div className="w-full h-2 bg-white/5 relative overflow-hidden">
                               <motion.div 
                                 initial={{ width: 0 }}
                                 animate={{ width: `${selectedNode.achievementProgress.percentage}%` }}
                                 className="absolute h-full bg-primary"
                               />
                             </div>
                           )}
                        </div>
                      ) : (
                        <>
                          <div className="space-y-8">
                             <h4 className="text-[10px] font-bold uppercase tracking-widest text-primary italic">Minimum Specs</h4>
                             <div className="space-y-6">
                                {selectedNode?.specs.map(spec => (
                                  <div key={spec.label} className="flex justify-between border-b border-white/5 pb-2 hover:bg-white/[0.02] transition-colors px-2">
                                     <span className="text-[9px] font-bold uppercase tracking-widest text-white/30 italic">{spec.label}</span>
                                     <p className="text-xs font-mono text-white/90">{spec.value}</p>
                                  </div>
                                ))}
                             </div>
                          </div>
    
                          <div className="space-y-8">
                             <h4 className="text-[10px] font-bold uppercase tracking-widest text-primary italic">Recommended Specs</h4>
                             <div className="space-y-6">
                                {selectedNode?.recommendedSpecs.map(spec => (
                                  <div key={spec.label} className="flex justify-between border-b border-white/5 pb-2 hover:bg-white/[0.02] transition-colors px-2">
                                     <span className="text-[9px] font-bold uppercase tracking-widest text-white/30 italic">{spec.label}</span>
                                     <p className="text-xs font-mono text-white/90">{spec.value}</p>
                                  </div>
                                ))}
                             </div>
                          </div>
                        </>
                      )}
                   </div>
                </div>

                <div className="lg:col-span-4 p-12 lg:p-16 flex flex-col">
                   <div className="flex items-center gap-4 mb-12">
                      <RefreshCw className="w-5 h-5 text-primary/40" />
                      <h3 className="text-[11px] font-bold uppercase tracking-[0.3em] italic text-white/60">Related Games</h3>
                   </div>
                   
                   <div className="space-y-8 flex-grow">
                      {selectedNode?.relatedGames.map(game => (
                        <div 
                          key={game.id} 
                          onClick={() => setSelectedNodeId(game.id)}
                          className="group flex gap-6 items-center cursor-pointer hover:bg-white/5 transition-all p-4 -mx-4 border border-transparent hover:border-white/10"
                        >
                           <div className="w-20 h-24 shrink-0 overflow-hidden transition-all">
                              <img src={game.image} className="w-full h-full object-cover" alt="" />
                           </div>
                           <div className="flex-grow space-y-2">
                              <h4 className="text-lg font-black uppercase tracking-tight group-hover:text-primary transition-colors">{game.title}</h4>
                              <div className="flex items-center gap-2 text-[9px] font-mono text-white/20 uppercase">
                                 <span>View Game</span>
                                 <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" />
                              </div>
                           </div>
                        </div>
                      ))}
                   </div>

                   <div className="mt-12 p-8 border border-white/5 bg-white/[0.02] flex flex-col items-center justify-center gap-4 opacity-40 hover:opacity-100 transition-all cursor-pointer">
                      <Search className="w-6 h-6 text-primary" />
                      <span className="text-[10px] font-black uppercase tracking-[0.3em]">Explore More</span>
                   </div>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function MetricBox({ label, value, sub }: { label: string; value: string; sub: string }) {
  return (
    <div className="bg-white/5 p-8 border border-white/10 hover:bg-white/10 transition-colors">
       <span className="text-[9px] font-bold uppercase tracking-widest text-primary block mb-4">{label}</span>
       <p className="text-4xl font-mono italic text-white/90 truncate">{value}</p>
       <span className="text-[8px] font-mono uppercase text-white/20 mt-2 block">{sub}</span>
    </div>
  );
}

function MetadataItem({ label, value, color = "text-white/80" }: { label: string; value?: string; color?: string }) {
  return (
    <div className="space-y-2">
       <span className="text-[8px] font-bold uppercase tracking-[0.3em] text-white/20 italic block">{label}</span>
       <p className={`text-sm font-black uppercase tracking-widest ${color} truncate`}>{value}</p>
    </div>
  );
}

function FilterChip({ label, active = false, onClick }: { label: string; active?: boolean; onClick?: () => void }) {
  return (
    <button 
      onClick={onClick}
      className={`px-6 py-2 border text-[10px] uppercase font-bold tracking-widest transition-colors ${
      active ? 'bg-primary text-black border-primary' : 'bg-transparent text-white/70 border-white/20 hover:border-white/60 hover:text-white'
    }`}>
      {label}
    </button>
  );
}

interface GameRowProps {
  title: string;
  image: string;
  status: 'INSTALLED' | 'AVAILABLE' | 'STEAM_CLOUD';
  hours: string;
  lastPlayed: string;
  liked: boolean;
  action: string;
  onClick: () => void;
}

const GameRow: React.FC<GameRowProps> = ({ title, image, status, hours, lastPlayed, liked, action, onClick }) => {
  return (
    <div 
      onClick={onClick}
      className="p-8 bg-background flex flex-col md:flex-row items-center gap-12 group hover:bg-white/[0.03] transition-colors cursor-pointer border-b border-white/5 last:border-b-0"
    >
      <div className="w-full md:w-32 h-40 shrink-0 bg-neutral-900 border border-white/10 overflow-hidden relative">
        <img 
          alt={title} 
          src={image} 
          className="w-full h-full object-cover transition-all duration-500 scale-110 group-hover:scale-100" 
          onError={(e) => {
            // Fallback to header if portrait is missing
            const target = e.target as HTMLImageElement;
            if (target.src.includes('library_600x900')) {
              target.src = target.src.replace('library_600x900.jpg', 'header.jpg');
            } else {
              target.src = 'https://images.unsplash.com/photo-1614013410980-6e1307224211?auto=format&fit=crop&q=80&w=400';
            }
          }}
        />
        <div className="absolute inset-0 bg-black/20 group-hover:bg-transparent transition-colors" />
      </div>
      
      <div className="flex-grow flex flex-col gap-4">
        <div className="flex justify-between items-start">
          <h3 className="text-3xl font-black uppercase tracking-tighter leading-none group-hover:text-primary transition-colors">{title}</h3>
          <button className={`transition-colors ${liked ? 'text-primary' : 'text-white/40 hover:text-primary'}`}>
            <Heart className={`w-6 h-6 ${liked ? 'fill-current' : ''}`} />
          </button>
        </div>

        <div className="flex flex-wrap gap-8 text-[9px] font-mono uppercase tracking-[0.2em] text-white/60">
          <div className="flex items-center gap-2 italic"><Clock className="w-3 h-3" /> {hours}</div>
          <div className="flex items-center gap-2"><RefreshCw className="w-3 h-3" /> {lastPlayed}</div>
          {status && <div className="text-primary border border-primary/20 bg-primary/5 px-2">Status: {status}</div>}
        </div>
      </div>

      <div className="w-full md:w-48">
        <div className={`w-full py-4 text-[10px] font-black uppercase tracking-[0.3em] transition-all border text-center ${
          action === 'Play' 
            ? 'bg-white text-black border-white group-hover:bg-primary group-hover:border-primary' 
            : 'bg-transparent text-white border-white/20 group-hover:border-white'
        }`}>
          {action} VIEW
        </div>
      </div>
    </div>
  );
}

